AllCops:
  Exclude:
    # Ignore HTML related things
    - '**/*.erb'
    # Ignore vendored gems
    - 'vendor/**/*'

Metrics/MethodLength:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

# DISABLED - used for converting to bool
Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
