azure_vm { 'spectestvm':
  ensure                        => running,
  image                         => 'canonical:ubuntuserver:14.04.2-LTS:latest',
  location                      => 'eastus',
  user                          => 'specuser',
  password                      => 'SpecPass123!@#$%',
  size                          => 'Standard_A0',
  resource_group                => 'puppettestresacc01',
  storage_account               => 'puppetteststoracc01',
  storage_account_type          => 'Standard_GRS',
  os_disk_name                  => 'osdisk01',
  os_disk_caching               => 'ReadWrite',
  os_disk_create_option         => 'FromImage',
  os_disk_vhd_container_name    => 'conttest1',
  os_disk_vhd_name              => 'vhdtest1',
  dns_domain_name               => 'mydomain01',
  dns_servers                   => '10.1.1.1 10.1.2.4',
  public_ip_allocation_method   => 'Dynamic',
  public_ip_address_name        => 'ip_name_test01pubip',
  virtual_network_name          => 'vnettest',
  virtual_network_address_space => '10.0.0.0/16',
  subnet_name                   => 'subnet111',
  subnet_address_prefix         => '10.0.2.0/24',
  ip_configuration_name         => 'ip_config_test01',
  private_ipallocation_method   => 'Dynamic',
  network_interface_name        => 'nicspec01',
}
