HOSTS:
  ubuntu-1404-x64:
    roles:
      - master
      - dashboard
      - database
      - agent
      - default
    platform: ubuntu-14.04-amd64
    box : puppetlabs/ubuntu-14.04-64-nocm
    box_url : https://vagrantcloud.com/puppetlabs/ubuntu-14.04-64-nocm
    hypervisor : vagrant
CONFIG:
  log_level: debug
  color: false
  consoleport: 443
  vagrant_memsize: 2048
  pe_dir: http://neptune.puppetlabs.lan/2015.2/ci-ready/
